#!/bin/bash

wd=`pwd`

export PATH=`dirname ${wd}`:$PATH
export LANG=C.UTF-8

nm='Zr'

echo "Calculating basic harmonic phonons"

mkdir -p harmonic
(cd harmonic
    ln -s ../opt/{INCAR,KPOINTS,SPOSCAR,POTCAR,vasprun.conf} .
    
    make-gen.py -o 1 -p $nm -n SPOSCAR -s 1.0 -b 0 > ${nm}_gen.in

    alm ${nm}_gen.in > ${nm}_gen.log
    
    displace.py --mag=0.02 --prefix=disp --VASP=SPOSCAR ${nm}.pattern_HARMONIC   
    
    run-calcs

    echo -n "Running vasp: "
    sleep 10
    while grep 'F=' calc-disp1/OSZICAR ; do 
        sleep 5
        echo -n '.'
    done
    echo ' done'

)


