#!/bin/bash

wd=`pwd`

export PATH=`dirname ${wd}`:$PATH
export LANG=C.UTF-8

nm='Zr'

echo "Calculating basic harmonic phonons"

mkdir -p harmonic
(cd harmonic
    ln -s ../opt/{INCAR,KPOINTS,SPOSCAR,POTCAR,vasprun.conf} .
    
    make-gen.py -o 1 -p $nm -n SPOSCAR -s 1.0 -b 0 > ${nm}_gen.in

    alm ${nm}_gen.in > ${nm}_gen.log
    
    displace.py --mag=0.02 --prefix=disp --VASP=SPOSCAR ${nm}.pattern_HARMONIC   
    
    run-calcs

    echo "Running vasp"
    sleep 5
    while true ; do 
        sleep 5
        if grep -q 'F=' calc-disp1/OSZICAR ; then 
            break
        else
            l=`tail -n 1 calc-disp1/OSZICAR|awk '{printf("(%2s)  %12s", $2, $4)}'`
            printf '\r VASP dE: %20s' "${l}"
        fi
    done
    echo ' done'

)


