#!/bin/bash

ALM=/opt/bin/alm

$prefix=$1
shift

n=$1
shift

for T in $* ; do
  mkdir -p T_$T
  (cd T_$T
    ln -s ../bin ../INCAR ../KPOINTS ../POTCAR ../SPOSCAR ../vasprun.conf .
    ln -s ../tdep_base base

    make-gen.py gen -p ${prefix} -n SPOSCAR > tdep_gen.in

    $ALM tdep_gen.in >tdep_gen.log

    make-disp.py -m base/${prefix}.msd -T $T -p SPOSCAR -n $n  disp

    run-calcs
  )
done


