#!/bin/bash

export LC_ALL=C.UTF-8

prefix=$1
shift

HAS_ASE=''
python -c 'import ase' 2>/dev/null >/dev/null && HAS_ASE=1

if [ -z "$HAS_ASE" ] ; then 
    echo "No ASE packages in the environment. Activate python env."
    exit 1
fi

for d in $* ; do
    (cd $d
        echo -n "Enter $d: "
#        if [ -f ${prefix}.bands ] ; then 
#            echo "${prefix}.bands present in $d. Sikipping processing."
#        else
            proc-calcs ${prefix}
#        fi
    )
    if [ -f ../exper.dat ] ; then 
        exper="--ex ../exper.dat"
    else
        exper=""
    fi
    plotband.py -u THz ${exper}  $d/${prefix}*.bands
    mv band_tmp.pdf band_${d}.pdf
    plotdos.py -u THz $d/${prefix}*.dos
    mv dos_tmp.pdf dos_${d}.pdf
done


