#!/bin/bash

for s in disp*.POSCAR ; do
    d=${s%%.POSCAR}
    echo -n  $d ": "
    mkdir calc-$d
    (
        cd calc-$d
        ln -s ../INCAR ../KPOINTS ../POTCAR ../vasprun.conf .
        ln -s ../$s POSCAR
        run-on-tsi /opt/bin/run-vasp541
    )
done
