#!/bin/bash

NAME=$1
RSC=$2
echo -n " ${NAME}:${RSC} "
qsub <<EOF
#!/bin/bash
#PBS -q batch
#PBS -N $NAME
#PBS -l ${RSC}

umask 0022

numprocs=\`wc -l <\$PBS_NODEFILE\`

cd \$PBS_O_WORKDIR
export OMP_NUM_THREADS=\$numprocs
mpirun.openmpi -np 1  /home/jochym/public/bin/anphon  RTA.in |tee RTA.log
# ~/Projects/alamode/develop/anphon/anphon  QHA_self.in |tee QHA_self.log

EOF
