#!/bin/bash

prefix=$1
nq=$2

if [ .$3 == "." ] ; then
    nodes="nodes=1:ppn=8"
else
    nodes=$3
fi


for (( k=0 ; k < ${nq} / 2 + 1 ; k=k+1 )) ; do
    q=`echo "$k / $nq" |bc -l`
    q=`printf "%7.6f" $q`
    for (( n=1 ; n<7 ; n=n+1 )) ; do 
        d=q_${q}_${n}
        if [ -d ${d} ] ; then 
            echo "Ready $d"
        else 
            mkdir -p $d
            (cd $d
                ln -s ../${prefix}.xml ../${prefix}.born .
                sed -e "s/q/${q}/g"  -e "s/n/${n}/g" < ../${prefix}_modes.in > ${prefix}_modes.in
                sed -e "s/nq/${nq}/g" < ../${prefix}.in > ${prefix}.in
                run-on-tsi "../run-anph ${d} ${node}"
                #anphon ${prefix}.in |tee ${prefix}.log
            )
        fi
    done
done
