#!/bin/bash

prefix=$1
p=$2
nq=$3
rsc=$4


for (( k=0 ; k < ${nq} / 2 + 1 ; k=k+1 )) ; do
    q=`echo "$k / $nq" |bc -l`
    q=`printf "%7.6f" $q`
    for (( n=1 ; n<7 ; n=n+1 )) ; do 
        d=q_${q}_${n}
        if [ -d ${d} ] ; then 
            echo "Ready $d"
        else 
            mkdir -p $d
            (cd $d
                ln -s ../QHA.xml ../QHA.born .
                sed -e "s/q/${q}/g"  -e "s/n/${n}/g" < ../${prefix}_modes.in > ${prefix}_modes.in
                sed -e "s/nq/${nq}/g" < ../ph_self.in > ph_self.in
                run-on-tsi "../run-anph ${p} ${d} ${rsc}"
            )
        fi
    done
done
