# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://jochym.github.io/almode-tools/"

git_url = "https://github.com/jochym/almode-tools/tree/main/"

def custom_doc_links(name): return None
